### ISSUE TITLE
各サイトから必要な情報をとってくる

### ISSUE THREAD

**Issue by kokoichi206** [android-project-46group/api#1]
各サイトから必要な情報をスクレイピングしてくる

- とりあえず、Json 形式？
- 画像も含めて

### TODO
- [x] Nogi: pic
- [x] Nogi: personal info
- [x] Sakura: pic
- [x] Sakura: personal info
- [x] Hinata: pic
- [x] Hinata: personal info

**Comment by kokoichi206** [comment]
参考
https://github.com/kokoichi206/python_practice/tree/main/scraping/personal_data_nogi

**Comment by kokoichi206** [comment]
全サイト、以下の形での情報取得を目指す

```json
{
	"akimotomanatsu": {
		"名前": "秋元 真夏",
		"生年月日": "1993年8月20日",
		"血液型": "B型",
		"星座": "しし座",
		"身長": "154cm",
	},
	"ikutaerika": {
		"名前": "生田 絵梨花",
		"生年月日": "1997年1月22日",
		"血液型": "A型",
		"星座": "みずがめ座",
		"身長": "160cm",
	},
        ...
```

**Comment by kokoichi206** [comment]
かなから、ラテン文字に変換する python のライブラリ

https://github.com/miurahr/pykakasi

```python
# うえむら りな -> uemurarina
def kana2latin(kana):
    kks = pykakasi.kakasi()
    result = kks.convert(kana)

    # [1] は半角スペースが入っている
    last = result[0]['hepburn']
    first = result[2]['hepburn']

    return last + first
```

hepburn っていうのは、ローマ字創始者の名前らしい([wiki](https://ja.wikipedia.org/wiki/%E3%83%98%E3%83%9C%E3%83%B3%E5%BC%8F%E3%83%AD%E3%83%BC%E3%83%9E%E5%AD%97))

**Comment by kokoichi206** [comment]
なぜか日向は大量にスペース（OR たぶ）が入った。
なんかの対策？

下は他と同じようにファイルに保存した時の例

```json
	},
	"yamaguchi": {
		"名前": "
                        山口 陽世
                      ",
		"
                            生年月日
                          ": "
                            2004年2月23日
                          ",
		"
                            星座
                          ": "
                            うお座
```
